[package]
name = "zpercent"
version = "0.1.0"
authors = ["shane"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "^1.3", features = ["fltk-bundled"] }
rand = "^0.8"
